services:
 app:
  build: .
  volumes:
   - .:/app
  ports:
   - 8000:8000
  image: app:django
  container_name: my_first_django_container
  command: python manage.py runserver 0.0.0.0:8000
  depends_on:
   - db
 db:
  image: postgres:14
  container_name: postgres-db
  environment:
   POSTGRES_DB: mydatabase
   POSTGRES_USER: fahad
   POSTGRES_PASSWORD: 12345678
  ports: 
   - 5432:5432
  volumes:
   - postgres_data:/var/lib/postgresql/data
volumes:
 postgres_data:
